"""Integration test for count_drugs() - the real function, the real Neo4j
driver, no fake session. Every test in test_graph_tool.py fakes the
driver, so none of them ever run graph_tool.py's own Cypher; they only
check what count_drugs() does with whatever a fake session hands back.

Needs a Neo4j instance reachable via the same NEO4J_* env vars
graph_tool.py itself reads, already loaded with
data/eval/ci_graph_seed.cypher (see block5_agent/load_ci_graph_seed.py) - which
is exactly what CI's "Load CI graph seed" step does before "Run tests" in
.github/workflows/ci.yml, so this runs there with no extra wiring. Skips
itself if that data isn't present, so a local `pytest` run against an
unrelated Neo4j instance (e.g. Block 3's own graph) doesn't fail for an
unrelated reason.

ci_graph_seed.cypher is generated by working backward from
data/eval/answer_key.json, so it can only ever reproduce a count
graph_tool.py's own verify+count logic already computed - it can't catch
a real bug in that logic (an AND that regressed to an OR, the wrong lab
property, a dropped clause), since the seed would just be regenerated to
match whatever the buggy code produces. block5_agent/generate_ci_graph_seed.py
adds one exception: a hand-written patient (_EDGE_CASE_PERSON_ID) who
genuinely has q7's condition (HAS_CONDITION) but fails its BMI check, and
carries a drug name used nowhere else in the seed. If verification's AND
ever regressed to an OR, this patient would wrongly pass and that drug
would wrongly appear below - something no answer-key-derived fixture
could ever catch.

The skip check below deliberately does NOT call count_drugs() itself to
decide whether the seed is loaded: q7 now verifies 25 real patients (up
from 1 at the original top_k=20 ceiling this test was first written
against), and an AND-regressed-to-OR bug in the verify query doesn't just
skip the lab check - Cypher's operator precedence also detaches the
`person_id IN $person_ids` clause from the comparison term it's AND'd
with, so the buggy query can match real patients outside the requested ID
list too. With 25 real matches now sharing q7's condition, that
side-effect is big enough to also throw off a baseline computed by
calling count_drugs() with a single real ID - the exact bug this test
exists to catch would then read as "seed not loaded" and skip silently
instead of failing loudly. Checking for the edge-case patient node
directly, over a raw driver connection that never touches
graph_tool.py's verify query, avoids that trap entirely.
"""
import os

import pytest
from dotenv import load_dotenv
from neo4j import GraphDatabase

from block5_agent.graph_tool import count_drugs

load_dotenv()

# q7 in data/eval/tasks.json.
_CONDITION = "Streptococcal pharyngitis"
_LAB = "BMI"
_COMPARISON = "below"
_VALUE = 25
# See block5_agent/generate_ci_graph_seed.py - one of q7's real verified
# patients (top_k=25, so q7 verifies 25 real patients; any one of them
# works here), and the hand-written patient who should always fail
# verification.
_REAL_VERIFIED_PATIENT_ID = 11146
_EDGE_CASE_PERSON_ID = 900001
_EDGE_CASE_DRUG_NAME = "ZZZ_Test_Excluded_Drug"


def _count_drugs_for_q7(person_ids):
    return count_drugs(
        person_ids, condition=_CONDITION, lab=_LAB, comparison=_COMPARISON, value=_VALUE
    )


def _ci_seed_is_loaded() -> bool:
    """A raw existence check for the edge-case patient node, independent
    of count_drugs()'s own verify query - so a bug in that query can
    never make this check itself unreliable (see module docstring)."""
    uri = os.environ.get("NEO4J_URI", "bolt://localhost:7687")
    user = os.environ.get("NEO4J_USER", "neo4j")
    password = os.environ.get("NEO4J_PASSWORD")
    database = os.environ.get("NEO4J_DATABASE", "neo4j")
    try:
        driver = GraphDatabase.driver(uri, auth=(user, password))
        try:
            with driver.session(database=database) as session:
                row = session.run(
                    "MATCH (p:Patient {person_id: $pid}) RETURN count(p) AS n",
                    pid=_EDGE_CASE_PERSON_ID,
                ).single()
        finally:
            driver.close()
    except Exception:
        return False
    return row["n"] == 1


def test_count_drugs_excludes_a_patient_who_fails_verification_on_live_data():
    if not _ci_seed_is_loaded():
        pytest.skip(
            "data/eval/ci_graph_seed.cypher doesn't look loaded into this "
            "Neo4j instance (no reachable Neo4j, or the edge-case fixture "
            "patient isn't present) - run block5_agent.load_ci_graph_seed first "
            "(CI does this automatically)"
        )

    baseline = _count_drugs_for_q7([_REAL_VERIFIED_PATIENT_ID])
    result = _count_drugs_for_q7([_REAL_VERIFIED_PATIENT_ID, _EDGE_CASE_PERSON_ID])

    assert _EDGE_CASE_DRUG_NAME not in result["drug_counts"]
    assert result["patients_checked"] == baseline["patients_checked"]
