"""Integration test for count_drugs() - the real function, the real Neo4j
driver, no fake session. Every test in test_graph_tool.py fakes the
driver, so none of them ever run graph_tool.py's own Cypher; they only
check what count_drugs() does with whatever a fake session hands back.

Needs a Neo4j instance reachable via the same NEO4J_* env vars
graph_tool.py itself reads, already loaded with
data/eval/ci_graph_seed.cypher (see scripts/load_ci_graph_seed.py) - which
is exactly what CI's "Load CI graph seed" step does before "Run tests" in
.github/workflows/ci.yml, so this runs there with no extra wiring. Skips
itself if that data isn't present, so a local `pytest` run against an
unrelated Neo4j instance (e.g. Block 3's own graph) doesn't fail for an
unrelated reason.

Leone's PR #4 review: ci_graph_seed.cypher is generated by working
backward from data/eval/answer_key.json, so it can only ever reproduce a
count graph_tool.py's own verify+count logic already computed - it can't
catch a real bug in that logic (an AND that regressed to an OR, the wrong
lab property, a dropped clause), since the seed would just be regenerated
to match whatever the buggy code produces. scripts/generate_ci_graph_seed.py
adds one exception: a hand-written patient (_EDGE_CASE_PERSON_ID) who
genuinely has q7's condition (HAS_CONDITION) but fails its BMI check, and
carries a drug name used nowhere else in the seed. If verification's AND
ever regressed to an OR, this patient would wrongly pass and that drug
would wrongly appear below - something no answer-key-derived fixture
could ever catch.
"""
import pytest

from scripts.graph_tool import GraphServiceError, count_drugs

# q7 in data/eval/tasks.json.
_CONDITION = "Streptococcal pharyngitis"
_LAB = "BMI"
_COMPARISON = "below"
_VALUE = 25
# See scripts/generate_ci_graph_seed.py - q7's one real verified patient,
# and the hand-written patient who should always fail verification.
_REAL_VERIFIED_PATIENT_ID = 8715
_EDGE_CASE_PERSON_ID = 900001
_EDGE_CASE_DRUG_NAME = "ZZZ_Test_Excluded_Drug"


def _count_drugs_for_q7(person_ids):
    return count_drugs(
        person_ids, condition=_CONDITION, lab=_LAB, comparison=_COMPARISON, value=_VALUE
    )


def test_count_drugs_excludes_a_patient_who_fails_verification_on_live_data():
    try:
        baseline = _count_drugs_for_q7([_REAL_VERIFIED_PATIENT_ID])
    except GraphServiceError as exc:
        pytest.skip(
            f"no reachable Neo4j instance ({exc.detail}) - CI loads and "
            "seeds one before this test runs"
        )
    if baseline["patients_checked"] != 1:
        pytest.skip(
            "data/eval/ci_graph_seed.cypher doesn't look loaded into this "
            "Neo4j instance - run scripts.load_ci_graph_seed first (CI "
            "does this automatically)"
        )

    result = _count_drugs_for_q7([_REAL_VERIFIED_PATIENT_ID, _EDGE_CASE_PERSON_ID])

    assert _EDGE_CASE_DRUG_NAME not in result["drug_counts"]
    assert result["patients_checked"] == baseline["patients_checked"]
